---
- name: Install Hyprland Packages
  community.general.pacman:
    state: present
    package:
      - cliphist
      - dunst
      - hyprland
      - hyprpaper
      - imagemagick
      - kitty
      - kitty-shell-integration
      - kitty-terminfo
      - network-manager-applet
      - nwg-look
      - pavucontrol
      - pamixer
      - ttf-jetbrains-mono-nerd
      - ttf-nerd-fonts-symbols
      - ttf-nerd-fonts-symbols-common
      - ttf-nerd-fonts-symbols-mono
      - udiskie
      - waybar
      - wl-clipboard
      - xdg-desktop-portal-hyprland

- name: Install Hypland Aur Packages
  tags: hyprland_aur
  become: false
  kewlfft.aur.aur:
    state: present
    use: paru
    name:
      - hypridle
      - hyprlock
      - hyprshot
      - rofi-lbonn-wayland
      - pasystray-wayland
      - pyprland
      - wlogout

- name: Set Up Gtk Themeing
  tags: gtk_themes
  block:
    - name: Install GTK Icon Theme
      community.general.pacman:
        state: present
        name: papirus-icon-theme

    - name: Install GTK Themes and Cursors
      become: false
      kewlfft.aur.aur:
        state: present
        use: paru
        name:
          - papirus-folders-catppuccin-git
          - catppuccin-cursors-mocha
          - catppuccin-cursors-macchiato
          - catppuccin-gtk-theme-mocha
          - catppuccin-gtk-theme-macchiato

    - name: Stow Gtk Configs
      become: false
      ansible.builtin.command:
        cmd: "/usr/bin/stow --adopt {{ item }}"
        chdir: "{{ dotfiles_path }}"
        creates: "{{ config_path }}/{{ item }}"
      with_items:
        - gtk

    - name: Enable Themes, Icons, Etc with Dconf
      become: false
      tags: dconf
      block:
        - name: Enable GTK Icon Theme
          community.general.dconf:
            key: "/org/gnome/desktop/interface/icon-theme"
            value: "'Papirus-Dark'"
            state: present

        - name: Enable Gtk Cursor Theme
          community.general.dconf:
            key: "/org/gnome/desktop/interface/cursor-theme"
            value: "'Catppuccin-Mocha-Blue-Cursors'"
            state: present

        - name: Set Gtk Cursor Size
          community.general.dconf:
            key: "/org/gnome/desktop/interface/cursor-size"
            value: 36
            state: present

        - name: Set Gtk Font AntiAliasing
          community.general.dconf:
            key: "/org/gnome/desktop/interface/font-antialiasing"
            value: "'rgba'"
            state: present

        - name: Set Gtk Theme
          community.general.dconf:
            key: "/org/gnome/desktop/interface/gtk-theme"
            value: "'Catppuccin-Macchiato-Standard-Blue-Dark'"
            state: present

- name: Stow Hyprland Configs
  become: false
  ansible.builtin.command:
    cmd: "/usr/bin/stow --adopt {{ item }}"
    chdir: "{{ dotfiles_path }}"
    creates: "{{ config_path }}/{{ item }}"
  with_items:
    - hyprland
    - waybar
    - rofi
    - dunst
    - kitty

- name: Install Gnome Keyring
  community.general.pacman:
    state: present
    package:
      - gnome-keyring
      - libsecret
      - seahorse

- name: Add Gnome Keyring to Pam Login
  ansible.builtin.lineinfile:
    path: /etc/pam.d/login
    line: "auth       optional     pam_gnome_keyring.so"
    insertafter: "^auth *include *system-local-login"

- name: Autostart Gnome Keyring after Session Login
  ansible.builtin.lineinfile:
    path: /etc/pam.d/login
    line: "session    optional     pam_gnome_keyring.so auto_start"
    insertafter: "^session *include *system-local-login"

- name: Enable User Service for gcr-ssh-agent
  become: false
  ansible.builtin.systemd_service:
    name: gcr-ssh-agent.service
    enabled: true
    state: restarted
    scope: user

- name: Install Polkit Packages
  community.general.pacman:
    name: polkit-gnome
    state: present

- name: Configure SDDM
  tags: sddm
  block:
    - name: Install SDDM
      community.general.pacman:
        state: present
        name: sddm

    - name: Install Catppuccin SDDM Theme Requirements
      community.general.pacman:
        state: present
        name:
          - qt5-svg
          - qt5-quickcontrols2

    - name: Get Catppuccin Github Api Object
      ansible.builtin.set_fact:
        catppuccin_sddm_obj: "{{ lookup('url', 'https://api.github.com/repos/catppuccin/sddm/releases/latest', split_lines=false) }}"

    - name: Unzip Catppuccin Theme to SDDM
      ansible.builtin.unarchive:
        remote_src: true
        src: "{{ item.browser_download_url }}"
        dest: "/usr/share/sddm/themes/"
        owner: root
        group: root
        mode: "0755"
      with_items: "{{ catppuccin_sddm_obj.assets }}"

    - name: Create sddm conf.d Directory
      ansible.builtin.file:
        state: directory
        path: /etc/sddm.conf.d
        owner: root
        group: root
        mode: "0755"

    - name: Create SDDM Conf File for Theme
      ansible.builtin.copy:
        dest: /etc/sddm.conf.d/catppuccin-theme.conf
        content: |
          [Theme]
          Current=catppuccin-mocha
        owner: root
        group: root
        mode: "0644"
# vim: ft=yaml.ansible
