---
- name: Install Hyprland Packages
  community.general.pacman:
    state: present
    package:
      - cliphist
      - dunst
      - hyprland
      - hyprpaper
      - kitty
      - kitty-shell-integration
      - kitty-terminfo
      - network-manager-applet
      - nwg-look
      - pavucontrol
      - ttf-jetbrains-mono-nerd
      - ttf-nerd-fonts-symbols
      - ttf-nerd-fonts-symbols-common
      - ttf-nerd-fonts-symbols-mono
      - udiskie
      - waybar
      - wl-clipboard
      - xdg-desktop-portal-hyprland

- name: Install Hypland Aur Packages
  become: false
  kewlfft.aur.aur:
    state: present
    use: paru
    name:
      - hypridle
      - hyprlock
      - rofi-lbonn-wayland
      - pyprland

- name: Install GTK Icon Theme
  tags: gtk_themes
  community.general.pacman:
    state: present
    name: papirus-icon-theme

- name: Install GTK Themes and Cursors
  become: false
  tags: gtk_themes
  kewlfft.aur.aur:
    state: present
    use: paru
    name:
      - papirus-folders-catppuccin-git
      - catppuccin-cursors-mocha
      - catppuccin-cursors-macchiato
      - catppuccin-gtk-theme-mocha
      - catppuccin-gtk-theme-macchiato

- name: Stow Hyprland Configs
  become: false
  ansible.builtin.command:
    cmd: "/usr/bin/stow --adopt {{ item }}"
    chdir: "{{ dotfiles_path }}"
    creates: "{{ config_path }}/{{ item }}"
  with_items:
    - hyprland
    - waybar
    - rofi
    - dunst
    - kitty

- name: Install Gnome Keyring
  community.general.pacman:
    state: present
    package:
      - gnome-keyring
      - libsecret
      - seahorse

- name: Add Gnome Keyring to Pam Login
  ansible.builtin.lineinfile:
    path: /etc/pam.d/login
    line: "auth       optional     pame_gnome_keyring.so"
    insertafter: "^auth *include *system-local-login"

- name: Autostart Gnome Keyring after Session Login
  ansible.builtin.lineinfile:
    path: /etc/pam.d/login
    line: "session    optional     pam_gnome_keyring.so auto_start"
    insertafter: "^session *include *system-local-login"

- name: Enable User Service for gcr-ssh-agent
  become: false
  ansible.builtin.systemd_service:
    name: gcr-ssh-agent.service
    enabled: true
    state: restarted
    scope: user

- name: Install Polkit Packages
  community.general.pacman:
    name: polkit-gnome
    state: present

# vim: ft=yaml.ansible
