---
- name: Install Hyprland Packages
  community.general.pacman:
    state: present
    package:
      - blueman
      - cliphist
      - dunst
      - hyprland
      - hyprpaper
      - kitty
      - kitty-shell-integration
      - kitty-terminfo
      - network-manager-applet
      - nwg-look
      - pavucontrol
      - ttf-jetbrains-mono-nerd
      - ttf-nerd-fonts-symbols
      - ttf-nerd-fonts-symbols-common
      - ttf-nerd-fonts-symbols-mono
      - udiskie
      - waybar
      - wl-clipboard
      - xdg-desktop-portal-hyprland

- name: Install Hypland Aur Packages
  become: false
  kewlfft.aur.aur:
    state: present
    use: paru
    name:
      - hypridle
      - hyprlock
      - rofi-lbonn-wayland
      - pyprland

- name: Stow Hyprland Configs
  become: false
  ansible.builtin.command:
    cmd: "/usr/bin/stow --adopt {{ item }}"
    chdir: "{{ dotfiles_path }}"
    creates: "{{ config_path }}/{{ item }}"
  with_items:
    - hyprland
    - waybar
    - rofi
    - dunst
    - kitty

# vim: ft=yaml.ansible
