---
- name: Arch Workstation Install
  hosts: arch
  remote_user: shadkaske
  become: true

  tasks:
    - name: Ilovecandy
      ansible.builtin.lineinfile:
        path: /etc/pacman.conf
        regexp: "^ILoveCandy"
        insertafter: "^#UseSyslog"
        line: "ILoveCandy"
# vim: ft=yaml.ansible
