---
- name: Arch Workstation Install
  hosts: arch
  remote_user: shadkaske
  connection: local
  become: true

  tasks:
    - name: Output Secret
      ansible.builtin.debug:
        msg: "{{ duo_secret_key }}"
# vim: ft=yaml.ansible
