---
- name: Arch Workstation Install
  hosts: arch
  remote_user: shadkaske
  become: true

  tasks:
    - name: Enable User Service for gcr-ssh-agent
      become: false
      ansible.builtin.systemd:
        name: gcr-ssh-agent.socket
        enabled: true
        state: started
        scope: user

    - name: Install Polkit Packages
      community.general.pacman:
        name: polkit-gnome
        state: present
# vim: ft=yaml.ansible
