---
- name: Arch Workstation Install
  hosts: arch
  remote_user: shadkaske
  connection: local
  become: true

  tasks:
    - name: Output Secret
      ansible.builtin.debug:
        msg: "{{ item.domain }}"
      when: item.domain != None
      with_items: "{{ code_repositories }}"
# vim: ft=yaml.ansible
