---
- name: Arch Workstation Install
  hosts: arch
  remote_user: shadkaske
  connection: local
  become: true

  tasks:
    - name: Install Gitflow
      community.general.pacman:
      # become: false
      # kewlfft.aur.aur:
        state: present
        name: imagemagick
        # use: paru
# vim: ft=yaml.ansible
