---
- name: Arch Workstation Install
  hosts: arch
  remote_user: shadkaske
  connection: local
  become: true

  tasks:
    - name: Install Gitflow
      become: false
      kewlfft.aur.aur:
        state: present
        name: gitflow-avh
        use: paru
# vim: ft=yaml.ansible
