---
- name: Arch Workstation Install
  hosts: arch
  remote_user: shadkaske
  connection: local
  become: true

  tasks:
    - name: Install Man Pages
      community.general.pacman:
        state: present
        name:
          - man-db
          - less
          - man-pages
# vim: ft=yaml.ansible
