---
- name: Arch Workstation Install
  hosts: arch
  remote_user: shadkaske
  become: true

  roles:
    - libvirt
    - user_config
    - hyprland
    - neovim

    # TODO: Configure Firewall
    # TODO: Tailscale
    # TODO: Duo
    # TODO: gnome-keyring
    # TODO: gnome-polkit
    # TODO: Repos
    # TODO: Configure Snapper
    # TODO: Install Apps
    # TODO: OneDrive

  pre_tasks:
    - name: Pacman and Updates
      tags: pacman
      block:
        - name: Pacman Use Color
          ansible.builtin.lineinfile:
            path: /etc/pacman.conf
            line: "Color"
            state: present
            regexp: "^#Color"

        - name: Pacman Use 5 Parallel Downloads
          ansible.builtin.lineinfile:
            path: /etc/pacman.conf
            line: "ParallelDownloads = 5"
            state: present
            regexp: "^#ParallelDownloads.*"

        - name: Ilovecandy
          ansible.builtin.lineinfile:
            path: /etc/pacman.conf
            regexp: "^ILoveCandy"
            insertafter: "^#UseSyslog"
            line: "ILoveCandy"

        - name: Install Reflector
          community.general.pacman:
            state: present
            package: reflector
            update_cache: true

        - name: Set Country Configuration in Reflector
          ansible.builtin.lineinfile:
            path: /etc/xdg/reflector/reflector.conf
            line: --country "United States"
            state: present
            regexp: "^# --country.*$"

        - name: Set Sorting for Reflector
          ansible.builtin.lineinfile:
            path: /etc/xdg/reflector/reflector.conf
            line: --sort rate
            state: present
            regexp: "--sort age"

        - name: Enable Reflector Timer
          ansible.builtin.systemd_service:
            name: reflector.timer
            state: started
            enabled: true

        - name: Run Reflector Service to Update Mirrors
          ansible.builtin.systemd_service:
            name: reflector.service
            state: started

        - name: Update Pacman Cache
          community.general.pacman:
            update_cache: true

        - name: Update System Packages
          community.general.pacman:
            upgrade: true

    - name: Install AMD GPU Packages
      community.general.pacman:
        state: present
        package:
          - mesa
          - lib32-mesa
          - vulkan-radeon
          - lib32-vulkan-radeon
          - libva-mesa-driver
          - lib32-libva-mesa-driver
          - mesa-vdpau
          - lib32-mesa-vdpau

    - name: Install PreRequisite Packages
      community.general.pacman:
        state: present
        package:
          - stow
          - docker
          - docker-compose
          - git
          - python
          - zsh
          - starship
          - tmux

    - name: Install AUR Helper
      block:
        - name: Allow Ansible User to use pacman
          ansible.builtin.lineinfile:
            path: /etc/sudoers.d/11-install-aur_helper
            line: "{{ ansible_ssh_user }} ALL=(ALL) NOPASSWD: /usr/bin/pacman"
            create: true
            mode: "0644"
            owner: root
            group: root
            validate: 'visudo -cf %s'

        - name: Install Paru
          become: false
          kewlfft.aur.aur:
            name: paru
            use: makepkg
            state: present
# vim: ft=yaml.ansible
