---
- name: Arch Workstation Install
  hosts: arch
  remote_user: shadkaske
  become: true

  roles:
    - libvirt
    - user_config
    - hyprland
    - neovim
    - applications
    - role: artis3n.tailscale
      tags: tailscale
      vars:
        tailscale_up_skip: true
    - role: duo
      tags: duo

  pre_tasks:
    - name: Pacman and Updates
      tags: pacman
      block:
        - name: Pacman Use Color
          ansible.builtin.lineinfile:
            path: /etc/pacman.conf
            line: "Color"
            state: present
            regexp: "^#Color"

        - name: Pacman Use 5 Parallel Downloads
          ansible.builtin.lineinfile:
            path: /etc/pacman.conf
            line: "ParallelDownloads = 5"
            state: present
            regexp: "^#ParallelDownloads.*"

        - name: Ilovecandy
          ansible.builtin.lineinfile:
            path: /etc/pacman.conf
            regexp: "^ILoveCandy"
            insertafter: "^#UseSyslog"
            line: "ILoveCandy"

        - name: Install Reflector
          community.general.pacman:
            state: present
            package: reflector
            update_cache: true

        - name: Set Country Configuration in Reflector
          ansible.builtin.lineinfile:
            path: /etc/xdg/reflector/reflector.conf
            line: --country "United States"
            state: present
            regexp: "^# --country.*$"

        - name: Set Sorting for Reflector
          ansible.builtin.lineinfile:
            path: /etc/xdg/reflector/reflector.conf
            line: --sort rate
            state: present
            regexp: "--sort age"

        - name: Enable Reflector Timer
          ansible.builtin.systemd_service:
            name: reflector.timer
            state: started
            enabled: true

        - name: Run Reflector Service to Update Mirrors
          ansible.builtin.systemd_service:
            name: reflector.service
            state: started

        - name: Update Pacman Cache
          community.general.pacman:
            update_cache: true

        - name: Update System Packages
          community.general.pacman:
            upgrade: true

    - name: Install AMD GPU Packages
      community.general.pacman:
        state: present
        package:
          - mesa
          - lib32-mesa
          - vulkan-radeon
          - lib32-vulkan-radeon
          - libva-mesa-driver
          - lib32-libva-mesa-driver
          - mesa-vdpau
          - lib32-mesa-vdpau

    - name: Install PreRequisite Packages
      community.general.pacman:
        state: present
        package:
          - stow
          - git
          - gitflow-avh
          - python
          - zsh
          - starship
          - tmux

    - name: Enable Docker Support
      tags: docker
      block:
        - name: Install Docker Packages
          community.general.pacman:
            state: present
            package:
              - docker
              - docker-compose

        - name: Enable and Start Docker Service
          ansible.builtin.systemd_service:
            state: restarted
            enabled: true
            name: docker.service

        - name: Add User to Docker Group
          ansible.builtin.user:
            name: "{{ ansible_ssh_user }}"
            groups: docker
            append: true

    - name: Install AUR Helper
      block:
        - name: Allow Ansible User to use pacman
          ansible.builtin.lineinfile:
            path: /etc/sudoers.d/11-install-aur_helper
            line: "{{ ansible_ssh_user }} ALL=(ALL) NOPASSWD: /usr/bin/pacman"
            create: true
            mode: "0644"
            owner: root
            group: root
            validate: 'visudo -cf %s'

        - name: Install Paru
          become: false
          kewlfft.aur.aur:
            name: paru
            use: makepkg
            state: present

  tasks:
    - name: Install Bluetooth Support
      tags: bluetooth
      block:
        - name: Install Bluetooth Packages
          community.general.pacman:
            state: present
            name:
              - bluez
              - bluez-utils
              - blueman

        - name: Enable and Start Bluetooth Service
          ansible.builtin.systemd_service:
            enabled: true
            state: restarted
            name: bluetooth.service

    - name: Enable Brightnessctl
      tags: brightness
      block:
        - name: Install Brightnessctl Package
          community.general.pacman:
            state: present
            name: brightnessctl

    - name: Sudo Configuration
      tags: sudo
      block:
        - name: Set Sudo Timestamp to Global
          ansible.builtin.copy:
            dest: /etc/sudoers.d/99-timestamp-type-global
            content: |
              Defaults timestamp_type=global
              Defaults timestamp_timeout=240
            owner: root
            group: root
            mode: "0660"

    - name: Clone Code Repositories
      tags: code, skip_ansible_lint
      become: false
      ansible.builtin.git:
        repo: "{{ item }}"
        dest: "/home/{{ ansible_ssh_user }}/Code/{{ item | basename | replace('.git', '') }}"
        clone: true
        update: false
        accept_newhostkey: true
      with_items: "{{ code_repositories }}"

    - name: Add Extra Groups to User
      tags: user_groups
      ansible.builtin.user:
        name: "{{ ansible_ssh_user }}"
        groups: uucp
        append: true
# vim: ft=yaml.ansible
