---
- name: Set up Firefox
  tags: firefox
  block:
    - name: Install Firefox
      community.general.pacman:
        state: present
        package:
          - firefox
          - gnu-free-fonts
          - noto-fonts
          - ttf-bitstream-vera
          - ttf-croscore
          - ttf-dejavu
          - ttf-droid
          - ttf-ibm-plex
          - ttf-liberation
          - ttf-mona-sans

    - name: Ensure the Firefox Policies Path Exists
      ansible.builtin.file:
        state: directory
        path: /etc/firefox/policies
        owner: root
        group: root
        mode: "0755"

    - name: Copy Firefox Policies
      ansible.builtin.copy:
        src: files/policies.json
        dest: /etc/firefox/policies/policies.json
        owner: root
        group: root
        mode: "0644"

- name: Install Kitty and Needed Packages
  community.general.pacman:
    state: present
    name:
      - kitty
      - kitty-shell-integration
      - kitty-terminfo
      - ttf-jetbrains-mono-nerd
      - ttf-nerd-fonts-symbols
      - ttf-nerd-fonts-symbols-common
      - ttf-nerd-fonts-symbols-mono
      - wl-clipboard

- name: Stow Application Configs
  become: false
  ansible.builtin.command:
    cmd: "/usr/bin/stow --adopt {{ item }}"
    chdir: "{{ dotfiles_path }}"
    creates: "{{ config_path }}/{{ item }}"
  with_items:
    - kitty

- name: Install Chrome
  become: false
  kewlfft.aur.aur:
    state: present
    use: paru
    name: google-chrome

- name: Install Man Pages
  community.general.pacman:
    state: present
    name:
      - man-db
      - less
      - man-pages

- name: Install Bitwarden
  tags: bitwarden
  community.general.pacman:
    state: present
    name: bitwarden

- name: Install System Utilites
  tags: utilities
  community.general.pacman:
    state: present
    name:
      - gnome-disk-utility
      - bind
      - minicom
      - bpytop
      - rsync
      - wireshark-qt

- name: Install Printer and Scanner Support
  tags: printing
  block:
    - name: Install Printer and Scanner Packages
      community.general.pacman:
        state: present
        name:
          - cups
          - cups-pdf
          - system-config-printer
          - cups-pk-helper
          - hplip
          - sane
          - simple-scan

    - name: Enable Cups Service
      ansible.builtin.systemd_service:
        name: cups.service
        enabled: true
        state: started

    - name: Allow passwordless printer admin through Polkit
      ansible.builtin.copy:
        dest: /etc/polkit-1/rules.d/49-allow-passwordless-printer-admin.rules
        content: |
          polkit.addRule(function(action, subject) {
            if (action.id == "org.opensuse.cupspkhelper.mechanism.all-edit" &&
                subject.isInGroup("wheel")){
                return polkit.Result.YES;
            }
          });
        owner: root
        group: root
        mode: "0600"

- name: Install libreoffice
  tags: libreoffice
  community.general.pacman:
    state: present
    name:
      - ttf-caladea
      - ttf-carlito
      - ttf-dejavu
      - ttf-liberation
      - ttf-linux-libertine-g
      - adobe-source-code-pro-fonts
      - adobe-source-sans-fonts
      - adobe-source-serif-fonts
      - hunspell
      - hunspell-en_us
      - libreoffice-still

- name: Install Work Applications
  tags: work_apps
  block:
    - name: Install IBM iAccess Client
      become: false
      kewlfft.aur.aur:
        state: present
        use: paru
        name: iacs

    - name: Install Onedrive Client
      tags: onedrive
      become: false
      kewlfft.aur.aur:
        state: present
        use: paru
        name: onedrive-abraunegg

    - name: Install DBeaver
      community.general.pacman:
        state: present
        name: dbeaver

    - name: Install Remmina
      community.general.pacman:
        state: present
        name:
          - freerdp
          - libvncserver
          - remmina
          - spice-gtk

- name: Install Personal Apps
  tags: personal_apps
  when: system_type == "personal"
  block:
    - name: Install Thunderbird
      community.general.pacman:
        state: present
        name: thunderbird

    - name: Install Private Internet Access Client
      become: false
      kewlfft.aur.aur:
        state: present
        use: paru
        name: piavpn-bin

    - name: Install Steam
      community.general.pacman:
        state: present
        name: steam
# vim: ft=yaml.ansible
