---
- name: Install ufw Packages
  community.general.pacman:
    state: present
    name: ufw

- name: Install UFW Docker AUR Package
  become: false
  kewlfft.aur.aur:
    state: present
    name: ufw-docker

- name: UFW - Disable IPV6
  ansible.builtin.lineinfile:
    path: /etc/ufw/ufw.conf
    line: IPV6=no
    state: present
    insertafter: EOF

- name: UFW - Allow Forwarding
  ansible.builtin.lineinfile:
    path: /etc/default/ufw
    regexp: '^DEFAULT_FORWARD_POLICY="DROP"'
    line: 'DEFAULT_FORWARD_POLICY="ACCEPT"'
    state: present

- name: Add ufw-docker After Rules to UFW
  tags: skip_ansible_lint
  ansible.builtin.command:
    cmd: /usr/bin/ufw-docker install

- name: UFW - SSH Limit
  community.general.ufw:
    rule: limit
    port: ssh
    proto: tcp
    state: enabled

- name: UFW - Allow SSH Inbound
  community.general.ufw:
    rule: allow
    name: SSH
    state: enabled

- name: UFW - Outgoing Allow
  community.general.ufw:
    state: enabled
    direction: outgoing
    policy: allow

- name: UFW - Set Default Incoming Policy to Deny
  community.general.ufw:
    default: deny
    state: enabled
    direction: incoming

- name: UFW - Enable Firewall
  ansible.builtin.systemd_service:
    name: ufw
    state: restarted
    enabled: true
# vim: ft=yaml.ansible
