---
- name: Install ufw Packages
  community.general.pacman:
    state: present
    name: ufw

- name: UFW - Disable IPV6
  ansible.builtin.lineinfile:
    path: /etc/ufw/ufw.conf
    line: IPV6=no
    state: present
    insertafter: EOF

- name: UFW - Allow Forwarding
  ansible.builtin.lineinfile:
    path: /etc/default/ufw
    regexp: '^DEFAULT_FORWARD_POLICY="DROP"'
    line: 'DEFAULT_FORWARD_POLICY="ACCEPT"'
    state: present

- name: UFW - Add After Rules for Docker
  ansible.builtin.blockinfile:
    path: /etc/ufw/after.rules
    insertafter: EOF
    block: |
      # BEGIN UFW AND DOCKER
      *filter
      :ufw-user-forward - [0:0]
      :ufw-docker-logging-deny - [0:0]
      :DOCKER-USER - [0:0]
      -A DOCKER-USER -j ufw-user-forward

      -A DOCKER-USER -j RETURN -s 10.0.0.0/8
      -A DOCKER-USER -j RETURN -s 172.16.0.0/12
      -A DOCKER-USER -j RETURN -s 192.168.0.0/16

      -A DOCKER-USER -p udp -m udp --sport 53 --dport 1024:65535 -j RETURN

      -A DOCKER-USER -j ufw-docker-logging-deny -p tcp -m tcp --tcp-flags FIN,SYN,RST,ACK SYN -d 192.168.0.0/16
      -A DOCKER-USER -j ufw-docker-logging-deny -p tcp -m tcp --tcp-flags FIN,SYN,RST,ACK SYN -d 10.0.0.0/8
      -A DOCKER-USER -j ufw-docker-logging-deny -p tcp -m tcp --tcp-flags FIN,SYN,RST,ACK SYN -d 172.16.0.0/12
      -A DOCKER-USER -j ufw-docker-logging-deny -p udp -m udp --dport 0:32767 -d 192.168.0.0/16
      -A DOCKER-USER -j ufw-docker-logging-deny -p udp -m udp --dport 0:32767 -d 10.0.0.0/8
      -A DOCKER-USER -j ufw-docker-logging-deny -p udp -m udp --dport 0:32767 -d 172.16.0.0/12

      -A DOCKER-USER -j RETURN

      -A ufw-docker-logging-deny -m limit --limit 3/min --limit-burst 10 -j LOG --log-prefix "[UFW DOCKER BLOCK] "
      -A ufw-docker-logging-deny -j DROP

      COMMIT
      # END UFW AND DOCKER

- name: UFW - SSH Limit
  community.general.ufw:
    rule: limit
    port: ssh
    proto: tcp
    state: enabled

- name: UFW - Allow SSH Inbound
  community.general.ufw:
    rule: allow
    name: SSH
    state: enabled

- name: UFW - Outgoing Allow
  community.general.ufw:
    state: enabled
    direction: outgoing
    policy: allow

- name: UFW - Set Default Incoming Policy to Deny
  community.general.ufw:
    default: deny
    state: enabled
    direction: incoming

- name: UFW - Enable Firewall
  ansible.builtin.systemd_service:
    name: ufw
    state: restarted
    enabled: true
# vim: ft=yaml.ansible
