---
- name: Pacman Use Color
  ansible.builtin.lineinfile:
    path: /etc/pacman.conf
    line: "Color"
    state: present
    regexp: "^#Color"

- name: Pacman Use 5 Parallel Downloads
  ansible.builtin.lineinfile:
    path: /etc/pacman.conf
    line: "ParallelDownloads = 5"
    state: present
    regexp: "^#ParallelDownloads.*"

- name: Ilovecandy
  ansible.builtin.lineinfile:
    path: /etc/pacman.conf
    regexp: "^ILoveCandy"
    insertafter: "^#UseSyslog"
    line: "ILoveCandy"

- name: Install Reflector
  community.general.pacman:
    state: present
    package: reflector
    update_cache: true

- name: Set Country Configuration in Reflector
  ansible.builtin.lineinfile:
    path: /etc/xdg/reflector/reflector.conf
    line: --country "United States"
    state: present
    regexp: "^# --country.*$"

- name: Set Sorting for Reflector
  ansible.builtin.lineinfile:
    path: /etc/xdg/reflector/reflector.conf
    line: --sort rate
    state: present
    regexp: "--sort age"

- name: Enable Reflector Timer
  ansible.builtin.systemd_service:
    name: reflector.timer
    state: started
    enabled: true

- name: Run Reflector Service to Update Mirrors
  ansible.builtin.systemd_service:
    name: reflector.service
    state: started

- name: Update Pacman Cache
  community.general.pacman:
    update_cache: true

- name: Update System Packages
  community.general.pacman:
    upgrade: true
# vim: ft=yaml.ansible
