---
- name: Install firewalld
  community.general.pacman:
    state: present
    name: firewalld

- name: Enable and Start Firewalld
  ansible.builtin.systemd_service:
    name: firewalld
    state: restarted
    enabled: true

- name: Restart Docker Service
  ansible.builtin.systemd_service:
    name: docker.service
    enabled: true
    state: restarted
# vim: ft=yaml.ansible
