---
- name: Install Nginx Proxy Manager Docker Container
  tags: proxy_manager
  block:
    - name: Create Docker Folder
      ansible.builtin.file:
        state: directory
        recurse: true
        path: "/home/{{ ansible_ssh_user }}/Code/docker/nginx-proxy-manager"
        owner: "{{ ansible_ssh_user }}"
        group: "{{ ansible_ssh_user }}"
        mode: "0775"

    - name: Copy Docker Compose for Nginx Proxy Manager
      ansible.builtin.template:
        src: nginx-proxy-manager.yml.j2
        dest: "/home/{{ ansible_ssh_user }}/Code/docker/nginx-proxy-manager/docker-compose.yml"
        owner: "{{ ansible_ssh_user }}"
        group: "{{ ansible_ssh_user }}"
        mode: "0664"

- name: Clone Code Repositories
  become: false
  ansible.builtin.git:
    repo: "{{ item }}"
    dest: "/home/{{ ansible_ssh_user }}/Code/{{ item | basename | replace('.git','') }}"
    clone: true
    update: false
    accept_newhostkey: true
  with_items: "{{ code_repositories }}"
# vim: ft=yaml.ansible
